In [1]:
import numpy as np

## DataTypes and Attributes

In [2]:
# actually numpy only have one datatype: ndarray
# n-dimensional-array
a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[11, 12, 13],
                [14, 15, 16],
                [17, 18, 19]]])

In [3]:
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
# forma (filas x columnas) de las matrices.
# para el caso de vectores (1D), los toma por defecto como columnas, y extrañamente no muestra el 1 de 1columna
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [8]:
# number of dimensions
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [9]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [10]:
# how many elements we have in total
a1.size, a2.size, a3.size

(3, 6, 18)

## Creating Arrays

In [11]:
# para mirar ayuda de una función, nos paramos en la mitad de los paréntensis del argumento de la función, y damos shift+tab
ones = np.ones((2, 3))
ones
zeros = np.zeros((4,4))

In [12]:
# start, end (not including it), step
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [13]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[2, 8, 0, 8, 9],
       [3, 2, 6, 7, 7],
       [3, 2, 8, 4, 8]])

In [14]:
random_array_float = np.random.random((5, 3))
random_array_float

array([[0.6508193 , 0.527861  , 0.47684754],
       [0.34645027, 0.52983694, 0.05482596],
       [0.49975017, 0.23918572, 0.82836895],
       [0.09092851, 0.8815865 , 0.43614283],
       [0.46930508, 0.25795132, 0.53751736]])

In [15]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.40535976, 0.5637782 , 0.49095639],
       [0.94013746, 0.94322618, 0.86583617],
       [0.23415918, 0.44573078, 0.762358  ],
       [0.31163632, 0.35928079, 0.1412428 ],
       [0.28510166, 0.04520873, 0.57930463]])

In [16]:
# new API for random numbers:  
# Generator uses bits provided by PCG64 which has better statistical properties than the legacy MT19937 used in RandomState
new_random = np.random.default_rng()  # Create a default Generator.
new_random.random(size=(2,3))  # Generate samples.

# The old functions in the numpy.random namespace will continue to work, 
# but they are considered "frozen", with no ongoing development. 
# If you are writing new code, and you don't have to support pre-1.17 versions of numpy, 
# it is recommended that you use the new random API

array([[0.60857571, 0.81013353, 0.36062635],
       [0.51719637, 0.76476674, 0.90932499]])

In [17]:
# The new Generator class does not have the rand() or random_sample() methods. 
# There is a uniform() method that allows you to specify the lower and upper bounds of the distribution.
new_random.uniform(1, 2, size=(2,2))

array([[1.5091013 , 1.87960622],
       [1.66137114, 1.10844665]])

In [18]:
# pseudo random => con seed
# la idea es obtener siempre los mismos números (random) -por si compartimos el notebook con un colega o algo así-
# reproducable random numbers
np.random.seed(seed=17)
seudoRandom = np.random.random((2, 3))
seudoRandom

array([[0.294665  , 0.53058676, 0.19152079],
       [0.06790036, 0.78698546, 0.65633352]])

## Viewing arrays

In [19]:
# mostrar elementos sin repetirlos
np.unique([1, 1, 2, 2, 3, 3, 4])

array([1, 2, 3, 4])

In [20]:
# mostrar filas de una matriz sin repetir
a = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])
np.unique(a, axis=0)

array([[1, 0, 0],
       [2, 3, 4]])

In [21]:
a3 # recordamos el array a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [22]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
# hasta el primer elemento -sin incluirlo, o sea a3[0]- (de la primera dimensión), 
# hasta la segunda fila (de la segunda dimensión),
# hasta la segunda columna (de la tercera dimensión)
a3[:1,:2,:2]

array([[[1, 2],
        [4, 5]]])

In [24]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[11, 12],
        [14, 15]]])

In [25]:
a4xx = np.random.randint(10, size=(2, 3, 4, 5))
a4xx

array([[[[4, 7, 1, 1, 9],
         [8, 2, 3, 6, 6],
         [9, 9, 1, 5, 1],
         [0, 5, 6, 6, 2]],

        [[6, 9, 8, 3, 2],
         [1, 9, 8, 3, 2],
         [7, 8, 9, 2, 1],
         [8, 1, 8, 0, 4]],

        [[5, 4, 4, 3, 3],
         [3, 7, 8, 5, 1],
         [9, 4, 9, 7, 3],
         [3, 1, 6, 1, 3]]],


       [[[8, 3, 2, 8, 2],
         [1, 0, 4, 8, 2],
         [1, 4, 4, 3, 6],
         [2, 8, 7, 5, 7]],

        [[3, 3, 9, 8, 7],
         [5, 8, 6, 4, 2],
         [2, 1, 8, 2, 6],
         [4, 9, 9, 5, 9]],

        [[2, 0, 2, 9, 1],
         [8, 1, 0, 5, 5],
         [6, 6, 5, 7, 2],
         [6, 8, 6, 0, 9]]]])

In [26]:
# ejercicio: mostrar solo la fila [8, 3, 2, 8, 2]
a4xx[1,0,0,:5]

array([8, 3, 2, 8, 2])

## Manipulating and Comparing arrays

In [27]:
# suma de matrices:
# del mismo tamaño y término a término
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [28]:
# multiplicación de término a término de matrices => ELEMENT WISE MULTIPLICATION
# mult_1 = np.array([1, 2, 3])
# ojo, las dimensiones de las matrices deben poder hacer el broadcast
mult_1 = np.array([[1, 2, 3],[4, 5, 6], [1, 1, 1]])
mult_2 = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
mult_1 * mult_2
# The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. 
# Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes

array([[ 1,  4,  9],
       [16, 25, 36],
       [ 7,  8,  9]])

In [29]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [30]:
# Floor division removes the decimals (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [31]:
# potenciación 
para_potenciacion = np.array([1, 2, 3])
para_potenciacion ** 3

array([ 1,  8, 27], dtype=int32)

In [32]:
# módulo con %
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

## Aggregation

In [33]:
# Aggregation = performing the same operation on a number of things

# Use Python's methods (`sum()`) on Python datatypes and 
# Use NumPy's methods on NumPy arrays (`np.sum()`). 

In [34]:
# Creative a massive NumPy array
massive_array = np.random.random(100000)

In [35]:
# magicFunctions start with "%"

# Mirando el desempeño de funciones de python y numpy para un elemento numpy
print('tiempo procesamiento de python')
%timeit sum(massive_array) # Python's sum()
print('tiempo procesamiento de numpy')
%timeit np.sum(massive_array) # NumPy's np.sum()

tiempo procesamiento de python
18.3 ms ± 535 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
tiempo procesamiento de numpy
47 µs ± 358 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [36]:
# Demo of std and var
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])
#
np.std(high_var_array), np.std(low_var_array)

(2072.711623024829, 2.8284271247461903)

## Reshaping and Transposing

In [37]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [38]:
a2_reshape = a2.reshape(2, 3, 1)
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [39]:
xxa = np.array([[1,2,3], [4,5,6]])
xxa

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
np.reshape(xxa, (3,-1))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
np.reshape(xxa, (6,-2))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [42]:
# Transpose = switches the axis'
np.reshape(xxa, (6,-2)).T

array([[1, 2, 3, 4, 5, 6]])

## Comparison Operators

In [43]:
a1

array([1, 2, 3])

In [44]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [45]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

## Sorting

In [46]:
random_array = np.random.randint(10, size=(3, 5))
random_array

array([[0, 1, 5, 5, 0],
       [6, 1, 9, 4, 6],
       [6, 7, 8, 5, 5]])

In [47]:
# ordenar de menor a mayor por fila
np.sort(random_array)

array([[0, 0, 1, 5, 5],
       [1, 4, 6, 6, 9],
       [5, 5, 6, 7, 8]])

In [48]:
# posiciones o índices de los números ordenados de menor a mayor por fila
# ACÁ MIRAR LAS ANOTACIONES EN ONENOTE PARA CLARIFICAR
np.argsort(random_array)

array([[0, 4, 1, 2, 3],
       [1, 3, 0, 4, 2],
       [3, 4, 0, 1, 2]], dtype=int64)

In [49]:
a1 = ([2, 5, 3])
a1

[2, 5, 3]

In [50]:
# índices de los elementos de menor a mayor
np.argsort(a1)

array([0, 2, 1], dtype=int64)

In [51]:
# índice del valor mínimo
np.argmin(a1)

0

In [52]:
# índice del valor máximo
np.argmax(a1)

1

In [53]:
random_array

array([[0, 1, 5, 5, 0],
       [6, 1, 9, 4, 6],
       [6, 7, 8, 5, 5]])

In [54]:
# índices del valor máximo de cada columna
np.argmax(random_array, axis=0)

array([1, 2, 1, 0, 1], dtype=int64)

In [55]:
# índices del valor máximo de cada fila
np.argmax(random_array, axis=1)

array([2, 2, 2], dtype=int64)

## Practical Example

In [56]:
# Turn an image into a NumPy array
from matplotlib.image import imread

fotoDaniel = imread("../fotos/daniel.png")


In [57]:
# PARA MOSTRAR LA FOTO ACÁ EN UN NOTEBOOK:
# <img src="../Fotos/daniel.png"/>

In [62]:
%%html
<img src="../fotos/daniel.png"/>

In [63]:
fotoDaniel.size, fotoDaniel.shape, fotoDaniel.ndim

(63700992, (3456, 4608, 4), 3)